##
## OPENVDB
##

set(COMPONENT_NAME openvdb)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})

set(OPENVDB_URL "https://github.com/AcademySoftwareFoundation/openvdb.git")
set(OPENVDB_VERSION "v11.0.0")

set(OPENVDB_ARGS ""
  -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}  
  #-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_FLAGS=-Wno-enum-constexpr-conversion
  -DCMAKE_C_FLAGS=-Wno-enum-constexpr-conversion
  -DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
  -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
  -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
  -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
  -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
  -DOPENVDB_BUILD_PYTHON_MODULE=OFF
  -DOPENVDB_BUILD_BINARIES=OFF
  -DOPENVDB_BUILD_VDB_PRINT=OFF
  -DUSE_NUMPY=OFF
  -DUSE_NANOVDB=ON
  -DOPENVDB_BUILD_PYTHON_LIBS=OFF
  -DPYILMBASE_ENABLE=OFF
  -DOPENVDB_VIEWERS_ENABLE=OFF
  #-DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}  #only needed if python libs are build
)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  GIT_REPOSITORY ${OPENVDB_URL}
  GIT_TAG       ${OPENVDB_VERSION}
  GIT_SHALLOW   ON
  CMAKE_ARGS
  ${OPENVDB_ARGS}
    BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  #BUILD_ALWAYS ${ALWAYS_REBUILD}
  BUILD_ALWAYS OFF
)

ExternalProject_Add_StepDependencies(${COMPONENT_NAME}
configure
  blosc
  boost
  $<$<BOOL:${BUILD_TBB}>:tbb>
)

add_to_prefix_path(${COMPONENT_PATH})