set(COMPONENT_NAME jpeg)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})
if (INSTALL_IN_SEPARATE_DIRECTORIES)
  set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE}/${COMPONENT_NAME})
endif()

set(JPEG_URL "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.0.1.zip")

set(JPEG_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
    -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
    -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
    -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
    -DWITH_SIMD=FALSE
)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  URL ${JPEG_URL}
  CMAKE_ARGS
  ${JPEG_ARGS}
    BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  BUILD_ALWAYS OFF
)

ExternalProject_Add_Step(${COMPONENT_NAME} install_bin
  COMMAND "${CMAKE_COMMAND}" -E copy_directory
  <BINARY_DIR>/bin ${COMPONENT_PATH}/bin
  DEPENDEES install
)

ExternalProject_Add_Step(${COMPONENT_NAME} include
  COMMAND "${CMAKE_COMMAND}" -E copy_directory
  <BINARY_DIR>/include ${COMPONENT_PATH}/include
  DEPENDEES install
)

ExternalProject_Add_Step(${COMPONENT_NAME} install_lib
  COMMAND "${CMAKE_COMMAND}" -E copy_directory
  #<BINARY_DIR>/lib64 ${COMPONENT_PATH}/lib
  <BINARY_DIR>/lib ${COMPONENT_PATH}/lib
  DEPENDEES install
)

