## Copyright 2019-2020 Intel Corporation
## SPDX-License-Identifier: Apache-2.0

set(COMPONENT_NAME openpgl)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})

set(OPENPGL_URL "git@github.com:intel-innersource/libraries.graphics.renderkit.openpgl.git")
set(OPENPGL_VERSION "devel")

set(OPENPGL_ARGS
-DCMAKE_PREFIX_PATH:PATH=${COMPONENT_PATH}
-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
-DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
-DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
-DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
-DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
-DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
)

#if(BUILD_STATIC)
set(OPENPGL_ARGS ${OPENPGL_ARGS}
  #-DBUILD_STATIC=${BUILD_STATIC}
  -DOPENPGL_BUILD_STATIC=ON
)
#endif()

if(TBB_ROOT)
set(OPENPGL_ARGS ${OPENPGL_ARGS}
  -DOPENPGL_TBB_ROOT=${TBB_ROOT}
)
endif()

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  GIT_REPOSITORY ${OPENPGL_URL}
  GIT_TAG       ${OPENPGL_VERSION}
  GIT_SHALLOW   OFF
  CMAKE_ARGS
  ${OPENPGL_ARGS}
    BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  #BUILD_ALWAYS ${ALWAYS_REBUILD}
  BUILD_ALWAYS OFF
)

ExternalProject_Add_StepDependencies(${COMPONENT_NAME}
configure
    $<$<BOOL:${BUILD_TBB}>:tbb>
)

add_to_prefix_path(${COMPONENT_PATH})
