##
## OpenEXR
##

set(COMPONENT_NAME openexr)

set(COMPONENT_PATH ${INSTALL_DIR_ABSOLUTE})

set(OPENEXR_URL "https://github.com/AcademySoftwareFoundation/openexr")
set(OPENEXR_VERSION "v2.3.0")

set(OPENEXR_ARGS ""
  -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}  
  #-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_INSTALL_PREFIX=${COMPONENT_PATH}
  -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_INSTALL_INCLUDEDIR}
  -DCMAKE_INSTALL_LIBDIR=${CMAKE_INSTALL_LIBDIR}
  -DCMAKE_INSTALL_DOCDIR=${CMAKE_INSTALL_DOCDIR}
  -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR}
  -DOPENEXR_BUILD_PYTHON_LIBS=OFF
  -DPYILMBASE_ENABLE=OFF
  -DOPENEXR_VIEWERS_ENABLE=OFF
  #-DBOOST_ROOT=${CMAKE_INSTALL_PREFIX}  #only needed if python libs are build
)

ExternalProject_Add(${COMPONENT_NAME}
  PREFIX ${COMPONENT_NAME}
  DOWNLOAD_DIR ${COMPONENT_NAME}
  STAMP_DIR ${COMPONENT_NAME}/stamp
  SOURCE_DIR ${COMPONENT_NAME}/src
  BINARY_DIR ${COMPONENT_NAME}/build
  GIT_REPOSITORY ${OPENEXR_URL}
  GIT_TAG       ${OPENEXR_VERSION}
  GIT_SHALLOW   ON
  CMAKE_ARGS
  ${OPENEXR_ARGS}
    BUILD_COMMAND ${DEFAULT_BUILD_COMMAND}
  #BUILD_ALWAYS ${ALWAYS_REBUILD}
  BUILD_ALWAYS OFF
)

add_to_prefix_path(${COMPONENT_PATH})